use crate::ast::*;
use std::collections::BTreeMap;

/// Generate a TLA+ specification whose `Next` actually models the program.
///
/// Each `→` becomes one step guarded by a program counter, so the flows fire in
/// source order and every space carries the value the previous step left. Shifts
/// are expanded with the same axis geometry the code generator uses, and each
/// `!` constraint becomes an invariant.
///
/// The spec is written for reading and for TLAPS. TLC cannot evaluate it when the
/// program divides or exponentiates, because those live in `Reals`; the generated
/// header says so.
pub fn generate_tla_spec(module_name: &str, block: &ToposBlock) -> String {
    generate_tla_spec_with_tau(module_name, block, 0.0)
}

/// As [`generate_tla_spec`], with the threshold symbol 𝜏 bound to `tau`.
pub fn generate_tla_spec_with_tau(module_name: &str, block: &ToposBlock, tau: f64) -> String {
    let ctx = Context::new(block, tau);
    let mut tla = String::new();

    tla.push_str(&format!(
        "---------------- MODULE {module_name} ----------------\n"
    ));
    let numeric = if ctx.needs_reals { "Reals" } else { "Integers" };
    tla.push_str(&format!("EXTENDS {numeric}, Sequences, TLC\n\n"));
    tla.push_str("\\* Generated by rhoc. Every flow is one step of Next, in source order.\n");
    if ctx.needs_reals {
        tla.push_str("\\* This program divides or uses fractional literals, so the spec lives in\n");
        tla.push_str("\\* Reals. TLC cannot evaluate real division: use it for reading and TLAPS.\n");
    } else {
        tla.push_str("\\* Instantiate Values with a small finite set to model check with TLC;\n");
        tla.push_str("\\* the generated .cfg does exactly that.\n");
    }
    tla.push('\n');

    tla.push_str("\\* The domain the caller's input is drawn from. Computed spaces are not\n");
    tla.push_str("\\* constrained to it, since arithmetic leaves any finite set.\n");
    tla.push_str("CONSTANT Values\n");
    tla.push_str("ASSUME Values # {} /\\ 0 \\in Values\n\n");
    tla.push_str("\\* A domain small enough to model check. The .cfg points Values here;\n");
    tla.push_str("\\* TLC's config grammar has no negative literals, so it lives in the module.\n");
    tla.push_str("ModelValues == {-1, 0, 1}\n\n");

    tla.push_str("\\* Grid geometry taken from the ◯ □ declarations.\n");
    tla.push_str(&format!("Shape == {}\n", tla_tuple(&ctx.shape)));
    tla.push_str(&format!("N == {}\n", ctx.elements));
    tla.push_str("Cells == 1..N\n");
    tla.push_str("Grid == [Cells -> Values]\n");
    tla.push_str("Zero == [i \\in Cells |-> 0]\n\n");

    if ctx.spaces.is_empty() {
        tla.push_str("\\* No spaces declared; nothing to model.\n");
        tla.push_str("====================================================\n");
        return tla;
    }

    let idents: Vec<String> = ctx.spaces.iter().map(|s| ctx.ident(s)).collect();
    let vars = idents.join(", ");

    let renamed: Vec<String> = ctx
        .spaces
        .iter()
        .filter(|s| ctx.ident(s) != **s)
        .map(|s| format!("\\* {} is {} in RHO source\n", ctx.ident(s), s))
        .collect();
    if !renamed.is_empty() {
        tla.push_str("\\* Identifier map (TLA+ names must be ASCII):\n");
        for line in &renamed {
            tla.push_str(line);
        }
        tla.push('\n');
    }
    tla.push_str(&format!("VARIABLES {vars}, pc\n"));
    tla.push_str(&format!("vars == <<{vars}, pc>>\n\n"));

    tla.push_str("\\* Only the program counter is constrained: a computed cell can hold any\n");
    tla.push_str("\\* value the arithmetic produces, not just one drawn from Values.\n");
    tla.push_str(&format!("TypeOK == pc \\in 0..{}\n\n", ctx.flows.len()));

    // Init: inputs are arbitrary grids, everything else starts at zero.
    tla.push_str("Init ==\n");
    for space in &ctx.spaces {
        let ident = ctx.ident(space);
        if ctx.sources.contains(space) {
            tla.push_str(&format!("  /\\ {ident} \\in Grid\n"));
        } else {
            tla.push_str(&format!("  /\\ {ident} = Zero\n"));
        }
    }
    tla.push_str("  /\\ pc = 0\n\n");

    // One action per flow, sequenced by pc.
    for (step, flow) in ctx.flows.iter().enumerate() {
        let unchanged: Vec<&String> = ctx
            .spaces
            .iter()
            .filter(|s| *s != &flow.target)
            .collect();

        tla.push_str(&format!("\\* {}\n", flow.comment));
        tla.push_str(&format!("Flow{} ==\n", step + 1));
        tla.push_str(&format!("  /\\ pc = {step}\n"));
        tla.push_str(&format!(
            "  /\\ {}' = [i \\in Cells |-> {}]\n",
            ctx.ident(&flow.target),
            ctx.value_expr(&flow.src, "i")
        ));
        tla.push_str(&format!("  /\\ pc' = {}\n", step + 1));
        if unchanged.is_empty() {
            tla.push_str("  /\\ TRUE\n\n");
        } else {
            let names: Vec<String> = unchanged.iter().map(|s| ctx.ident(s)).collect();
            tla.push_str(&format!("  /\\ UNCHANGED <<{}>>\n\n", names.join(", ")));
        }
    }

    tla.push_str("\\* The grid has converged; the kernel has nothing left to do.\n");
    tla.push_str(&format!("Converged ==\n  /\\ pc = {}\n", ctx.flows.len()));
    tla.push_str("  /\\ UNCHANGED vars\n\n");

    let actions: Vec<String> = (1..=ctx.flows.len()).map(|i| format!("Flow{i}")).collect();
    tla.push_str("Next ==\n");
    if actions.is_empty() {
        tla.push_str("  Converged\n\n");
    } else {
        tla.push_str(&format!("  \\/ {}\n", actions.join("\n  \\/ ")));
        tla.push_str("  \\/ Converged\n\n");
    }

    tla.push_str("Spec == Init /\\ [][Next]_vars /\\ WF_vars(Next)\n\n");

    // ! (EXPR) becomes an invariant over the whole grid.
    if ctx.constraints.is_empty() {
        tla.push_str("\\* No ! constraints in the source.\n");
        tla.push_str("Invariant == TypeOK\n\n");
    } else {
        tla.push_str("\\* Invariants from the ! constraints.\n");
        for (n, expr) in ctx.constraints.iter().enumerate() {
            tla.push_str(&format!(
                "Constraint{} == \\A i \\in Cells : {}\n",
                n + 1,
                ctx.pred_expr(expr, "i")
            ));
        }
        let names: Vec<String> = (1..=ctx.constraints.len())
            .map(|i| format!("Constraint{i}"))
            .collect();
        tla.push_str(&format!(
            "Invariant == TypeOK /\\ ({})\n\n",
            names.join(" /\\ ")
        ));
    }

    tla.push_str("\\* The pipeline always reaches its equilibrium point.\n");
    tla.push_str(&format!(
        "Termination == <>(pc = {})\n\n",
        ctx.flows.len()
    ));

    tla.push_str("====================================================\n");
    tla
}

struct Flow {
    target: String,
    src: Expr,
    comment: String,
}

struct Context {
    spaces: Vec<String>,
    sources: Vec<String>,
    shape: Vec<usize>,
    elements: usize,
    flows: Vec<Flow>,
    constraints: Vec<Expr>,
    tau: f64,
    needs_reals: bool,
    shapes: BTreeMap<String, Vec<usize>>,
    /// RHO space name -> a legal TLA+ identifier. SANY only accepts ASCII
    /// letters, digits and underscore, so glyph names like △ need mapping.
    names: BTreeMap<String, String>,
}

impl Context {
    fn new(block: &ToposBlock, tau: f64) -> Self {
        let mut shapes: BTreeMap<String, Vec<usize>> = BTreeMap::new();
        let mut spaces = Vec::new();
        let mut sources = Vec::new();

        let record = |name: &str, list: &mut Vec<String>| {
            if !list.iter().any(|n| n == name) {
                list.push(name.to_string());
            }
        };

        for stmt in &block.statements {
            match stmt {
                Statement::SpaceDef(decl) => {
                    shapes.insert(decl.name.clone(), decl.dimensions.clone());
                    record(&decl.name, &mut spaces);
                    record(&decl.name, &mut sources);
                }
                Statement::ExtBind(bind) => {
                    shapes.insert(bind.space.name.clone(), bind.space.dimensions.clone());
                    record(&bind.space.name, &mut spaces);
                    record(&bind.space.name, &mut sources);
                }
                _ => {}
            }
        }

        let primary = shapes
            .get("INPUT")
            .cloned()
            .or_else(|| shapes.values().next().cloned())
            .unwrap_or_else(|| vec![4]);

        let mut flows = Vec::new();
        let mut constraints = Vec::new();
        for stmt in &block.statements {
            match stmt {
                Statement::Flow { src, target } => {
                    let name = match target {
                        FlowTarget::Var(n) => n.clone(),
                        FlowTarget::Equilibrium => "OUTPUT".to_string(),
                    };
                    record(&name, &mut spaces);
                    // A flow target that was never declared inherits the grid.
                    shapes.entry(name.clone()).or_insert_with(|| primary.clone());
                    let comment = match target {
                        FlowTarget::Var(n) => format!("{} → {n}", expr_glyphs(src)),
                        FlowTarget::Equilibrium => {
                            format!("{} → = (equilibrium)", expr_glyphs(src))
                        }
                    };
                    flows.push(Flow {
                        target: name,
                        src: src.clone(),
                        comment,
                    });
                }
                Statement::Constraint(expr) => constraints.push(expr.clone()),
                _ => {}
            }
        }

        // Sources are only the spaces no flow ever writes.
        sources.retain(|s| !flows.iter().any(|f| &f.target == s));

        let elements = primary.iter().product::<usize>().max(1);

        // Division and fractional literals are only defined in Reals, which TLC
        // cannot evaluate; everything else stays in Integers and is checkable.
        let needs_reals = flows.iter().any(|f| uses_reals(&f.src))
            || constraints.iter().any(uses_reals)
            || tau != tau.trunc();

        let mut names: BTreeMap<String, String> = BTreeMap::new();
        let mut taken: Vec<String> = RESERVED.iter().map(|s| s.to_string()).collect();
        for space in &spaces {
            let mut ident = sanitize_tla_ident(space);
            while taken.contains(&ident) {
                ident.push('_');
            }
            taken.push(ident.clone());
            names.insert(space.clone(), ident);
        }

        Self {
            spaces,
            sources,
            shape: primary,
            elements,
            flows,
            constraints,
            tau,
            needs_reals,
            shapes,
            names,
        }
    }

    fn ident(&self, name: &str) -> String {
        self.names
            .get(name)
            .cloned()
            .unwrap_or_else(|| sanitize_tla_ident(name))
    }

    fn shape_of(&self, name: &str) -> Vec<usize> {
        self.shapes
            .get(name)
            .filter(|s| s.iter().product::<usize>() == self.elements)
            .cloned()
            .unwrap_or_else(|| self.shape.clone())
    }

    /// Pointwise value of an expression at index `i`.
    fn value_expr(&self, expr: &Expr, i: &str) -> String {
        match expr {
            Expr::Number(v) => format_number(*v),
            Expr::Var(name) if is_tau(name) => format_number(self.tau),
            Expr::Var(name) => format!("{}[{i}]", self.ident(name)),
            Expr::AuditTrace(inner) => self.value_expr(inner, i),
            Expr::Shift { dir, axis, operand } => self.shift_expr(operand, *dir, *axis, i),
            Expr::BinaryOp { op, lhs, rhs } => {
                let l = self.value_expr(lhs, i);
                let r = self.value_expr(rhs, i);
                match op {
                    BinaryOpKind::Add => format!("({l} + {r})"),
                    BinaryOpKind::Sub => format!("({l} - {r})"),
                    BinaryOpKind::Mul => format!("({l} * {r})"),
                    BinaryOpKind::Div => format!("({l} / {r})"),
                    BinaryOpKind::Pow => format!("({l} ^ {r})"),
                    // A comparison masks the grid rather than yielding a boolean.
                    _ => format!(
                        "(IF {l} {} {r} THEN {l} ELSE 0)",
                        tla_compare(op)
                    ),
                }
            }
        }
    }

    fn shift_expr(&self, operand: &Expr, dir: ShiftDir, axis: Option<usize>, i: &str) -> String {
        let Some(name) = place_name(operand) else {
            return "0".to_string();
        };
        let shape = self.shape_of(&name);
        let Some((stride, extent)) = axis_geometry(&shape, axis) else {
            return "0".to_string();
        };
        if extent <= 1 {
            return "0".to_string();
        }
        // Cells are 1-based in TLA+, so the position uses i-1.
        let pos = if stride == 1 {
            format!("(({i} - 1) % {extent})")
        } else {
            format!("(((({i} - 1) \\div {stride})) % {extent})")
        };
        match dir {
            ShiftDir::Positive => {
                format!("(IF {pos} = 0 THEN 0 ELSE {}[{i} - {stride}])", self.ident(&name))
            }
            ShiftDir::Negative => format!(
                "(IF {pos} = {} THEN 0 ELSE {}[{i} + {stride}])",
                extent - 1,
                self.ident(&name)
            ),
        }
    }

    /// A `!` constraint reads as a predicate, not as a masking value.
    fn pred_expr(&self, expr: &Expr, i: &str) -> String {
        match expr {
            Expr::BinaryOp { op, lhs, rhs }
                if matches!(
                    op,
                    BinaryOpKind::Gt
                        | BinaryOpKind::Lt
                        | BinaryOpKind::Gte
                        | BinaryOpKind::Lte
                        | BinaryOpKind::Eq
                ) =>
            {
                format!(
                    "{} {} {}",
                    self.value_expr(lhs, i),
                    tla_compare(op),
                    self.value_expr(rhs, i)
                )
            }
            Expr::AuditTrace(inner) => self.pred_expr(inner, i),
            other => format!("{} # 0", self.value_expr(other, i)),
        }
    }
}

/// Whether an expression needs the Reals module rather than Integers.
fn uses_reals(expr: &Expr) -> bool {
    match expr {
        Expr::Number(v) => *v != v.trunc(),
        Expr::Var(_) => false,
        Expr::AuditTrace(inner) => uses_reals(inner),
        Expr::Shift { operand, .. } => uses_reals(operand),
        Expr::BinaryOp { op, lhs, rhs } => {
            matches!(op, BinaryOpKind::Div) || uses_reals(lhs) || uses_reals(rhs)
        }
    }
}

/// The TLC configuration that goes with a generated spec.
pub fn generate_tla_config(block: &ToposBlock) -> String {
    generate_tla_config_with_tau(block, 0.0)
}

/// As [`generate_tla_config`], with 𝜏 bound to `tau`.
pub fn generate_tla_config_with_tau(block: &ToposBlock, tau: f64) -> String {
    let ctx = Context::new(block, tau);
    let mut cfg = String::new();
    cfg.push_str("\\* Generated by rhoc. Run with:\n");
    cfg.push_str("\\*   java -jar tla2tools.jar rho_harmony.tla\n");
    if ctx.needs_reals {
        cfg.push_str("\\* NOTE: this program divides, so the spec is over Reals and TLC\n");
        cfg.push_str("\\* cannot evaluate it. SANY will still parse the module.\n");
    }
    cfg.push_str("\nSPECIFICATION Spec\n");
    cfg.push_str("CONSTANT Values <- ModelValues\n");
    cfg.push_str("INVARIANT Invariant\n");
    cfg.push_str("PROPERTY Termination\n");
    cfg
}

fn tla_compare(op: &BinaryOpKind) -> &'static str {
    match op {
        BinaryOpKind::Gt => ">",
        BinaryOpKind::Lt => "<",
        BinaryOpKind::Gte => ">=",
        BinaryOpKind::Lte => "<=",
        BinaryOpKind::Eq => "=",
        _ => "=",
    }
}

fn tla_tuple(dims: &[usize]) -> String {
    let parts: Vec<String> = dims.iter().map(|d| d.to_string()).collect();
    format!("<<{}>>", parts.join(", "))
}

fn format_number(v: f64) -> String {
    if v == v.trunc() && v.abs() < 1e15 {
        format!("{}", v as i64)
    } else {
        format!("{v}")
    }
}

fn is_tau(name: &str) -> bool {
    name == "𝜏" || name == "τ"
}

fn place_name(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Var(name) => Some(name.clone()),
        Expr::AuditTrace(inner) => place_name(inner),
        _ => None,
    }
}

/// Render an expression back in RHO glyphs, for the comment above each action.
fn expr_glyphs(expr: &Expr) -> String {
    match expr {
        Expr::Number(v) => format_number(*v),
        Expr::Var(name) => name.clone(),
        Expr::AuditTrace(inner) => format!("$ {}", expr_glyphs(inner)),
        Expr::Shift { dir, axis, operand } => match axis {
            Some(a) => format!("{dir}{a}{}", expr_glyphs(operand)),
            None => format!("{dir}{}", expr_glyphs(operand)),
        },
        Expr::BinaryOp { op, lhs, rhs } => {
            format!("({} {} {})", expr_glyphs(lhs), op, expr_glyphs(rhs))
        }
    }
}

/// Definitions this generator emits; a space may not collide with them.
const RESERVED: &[&str] = &[
    "Shape", "N", "Cells", "Grid", "Zero", "vars", "pc", "TypeOK", "Init",
    "Converged", "Next", "Spec", "Invariant", "Termination", "Real", "Nat",
    "Int", "TRUE", "FALSE", "IF", "THEN", "ELSE", "MODULE", "EXTENDS",
    "VARIABLES", "CONSTANT", "CONSTANTS", "ASSUME", "THEOREM", "UNCHANGED",
];

/// SANY identifiers are ASCII letters, digits and underscore, starting with a
/// letter. Glyph names are escaped by code point so the mapping stays injective.
fn sanitize_tla_ident(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push_str(&format!("u{:04X}", ch as u32));
        }
    }
    if out.is_empty() || !out.starts_with(|c: char| c.is_ascii_alphabetic()) {
        out.insert(0, 'S');
    }
    out
}
